"""
HTTP API connector for remote farmer audio sources.

This connector replaces SSH/SFTP with HTTP API calls to the farmer's
external data source server. The farmer provides:
  - Base URL (e.g., https://abc123.ngrok-free.dev)
  - API Key (UUID generated by the farmer's server)

The poller calls list_recordings() to discover new files and
download_file_bytes() to fetch audio data for processing.
"""

from typing import Optional
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry


def _build_session(api_key: str, timeout: int = 30) -> requests.Session:
    """
    Create a requests Session with retry logic and authentication.
    
    Args:
        api_key: The API key provided by the farmer
        timeout: Request timeout in seconds
    
    Returns:
        Configured requests.Session
    """
    session = requests.Session()
    
    # Add API key to all requests
    session.headers.update({"X-API-Key": api_key})
    
    # Configure retry strategy
    retry_strategy = Retry(
        total=3,
        backoff_factor=1,
        status_forcelist=[429, 500, 502, 503, 504],
        allowed_methods=["GET", "POST"]
    )
    
    adapter = HTTPAdapter(max_retries=retry_strategy)
    session.mount("http://", adapter)
    session.mount("https://", adapter)
    
    return session


def test_connection(config: dict) -> dict:
    """
    Test the HTTP API connection to the farmer's server.
    
    Args:
        config: Connection config dict with keys:
            - api_base_url: Base URL of the farmer's server
            - api_key: API key for authentication
    
    Returns:
        {"ok": True} or {"ok": False, "error": "<message>"}
    """
    try:
        base_url = config.get("api_base_url", "").rstrip("/")
        api_key = config.get("api_key", "")
        
        if not base_url:
            return {"ok": False, "error": "api_base_url is required"}
        if not api_key:
            return {"ok": False, "error": "api_key is required"}
        
        session = _build_session(api_key, timeout=10)
        
        # Test health endpoint
        health_response = session.get(f"{base_url}/health", timeout=10)
        health_response.raise_for_status()
        
        # Test recordings list endpoint (requires auth)
        recordings_response = session.get(f"{base_url}/recordings", timeout=10)
        recordings_response.raise_for_status()
        
        return {"ok": True}
    
    except requests.exceptions.HTTPError as exc:
        if exc.response.status_code == 401:
            return {"ok": False, "error": "Invalid API key (401 Unauthorized)"}
        return {"ok": False, "error": f"HTTP {exc.response.status_code}: {exc}"}
    
    except requests.exceptions.ConnectionError as exc:
        return {"ok": False, "error": f"Connection failed: {exc}"}
    
    except requests.exceptions.Timeout as exc:
        return {"ok": False, "error": f"Request timeout: {exc}"}
    
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


def list_recordings(config: dict, hive_id: str = None) -> list[str]:
    """
    List available audio recordings from the farmer's server.
    
    Args:
        config: Connection config dict with keys:
            - api_base_url: Base URL of the farmer's server
            - api_key: API key for authentication
        hive_id: Optional hive ID to filter recordings for a specific hive
    
    Returns:
        List of recording paths (e.g., ["hive-id/file1.wav", "hive-id/file2.wav"])
    
    Raises:
        requests.exceptions.RequestException: On connection or HTTP errors
    """
    base_url = config.get("api_base_url", "").rstrip("/")
    api_key = config.get("api_key", "")
    
    if not base_url or not api_key:
        raise ValueError("api_base_url and api_key are required in config")
    
    session = _build_session(api_key)
    params = {"hive_id": hive_id} if hive_id else {}
    response = session.get(f"{base_url}/recordings", params=params, timeout=30)
    response.raise_for_status()
    
    data = response.json()
    return data.get("recordings", [])


def download_file_bytes(config: dict, filepath: str) -> bytes:
    """
    Download a single audio file from the farmer's server.
    
    Args:
        config: Connection config dict with keys:
            - api_base_url: Base URL of the farmer's server
            - api_key: API key for authentication
        filepath: Path to the file (e.g., "hive-id/filename.wav")
    
    Returns:
        Audio file contents as bytes
    
    Raises:
        requests.exceptions.RequestException: On connection or HTTP errors
    """
    base_url = config.get("api_base_url", "").rstrip("/")
    api_key = config.get("api_key", "")
    
    if not base_url or not api_key:
        raise ValueError("api_base_url and api_key are required in config")
    
    session = _build_session(api_key)
    response = session.get(
        f"{base_url}/recordings/{filepath}",
        timeout=60,  # Longer timeout for file downloads
        stream=True
    )
    response.raise_for_status()
    
    # Read the entire file into memory
    return response.content


def get_recording_url(config: dict, filepath: str) -> str:
    """
    Construct the full URL for a recording file.
    
    This is used as the source_url identifier in AudioSource records.
    
    Args:
        config: Connection config dict with api_base_url
        filepath: Path to the file (e.g., "hive-id/filename.wav")
    
    Returns:
        Full URL to the recording (e.g., "https://server.com/recordings/hive-id/file.wav")
    """
    base_url = config.get("api_base_url", "").rstrip("/")
    return f"{base_url}/recordings/{filepath}"


def create_hive_folder(config: dict, hive_folder: str) -> dict:
    """
    Create a hive folder on the farmer's server for organizing recordings.
    
    This is called automatically when a hive is created in BSADS to ensure
    the folder structure exists on the farmer's server.
    
    Args:
        config: Connection config dict with keys:
            - api_base_url: Base URL of the farmer's server
            - api_key: API key for authentication
        hive_folder: Name of the hive folder to create (e.g., "Hive 001")
    
    Returns:
        Response dict with folder_path and created status
    
    Raises:
        requests.exceptions.RequestException: On connection or HTTP errors
    """
    base_url = config.get("api_base_url", "").rstrip("/")
    api_key = config.get("api_key", "")
    
    if not base_url or not api_key:
        raise ValueError("api_base_url and api_key are required in config")
    
    session = _build_session(api_key)
    response = session.post(
        f"{base_url}/folders/{hive_folder}",
        timeout=30
    )
    response.raise_for_status()
    
    return response.json()
